version: 2

jobs:

  build_setup:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/puj
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f2:99:0d:3d:49:06:5c:73:d9:77:2e:1a:0f:30:90:66"
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/puj
          key: puj-ci-stuff-{{ checksum ".circle-sha" }}

  unit_test:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/puj
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - puj-ci-stuff-{{ checksum ".circle-sha" }}
      - run: lein test


workflows:
  version: 2
  build:
    jobs:
      - build_setup
      - unit_test:
          requires:
            - build_setup
